CREATE TABLE ia_configuracoes (
    id SERIAL PRIMARY KEY,
    empresa VARCHAR(255) NOT NULL,
    nome_ia VARCHAR(255) NOT NULL,
    cnpj VARCHAR(20) NOT NULL,
    segmento VARCHAR(255) NOT NULL,
    numero_filiais VARCHAR(100) NOT NULL,
    numero_delivery VARCHAR(30) NOT NULL,
    horario_atendimento VARCHAR(255) NOT NULL,
    responsavel VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(30) NOT NULL,
    volume_atendimentos VARCHAR(255) NOT NULL,
    canais_atendimento VARCHAR(255) NOT NULL,
    sistemas_integrados VARCHAR(255) NOT NULL,
    objetivos_ia TEXT NOT NULL,
    tom_de_voz TEXT NOT NULL,
    palavras_chave TEXT NOT NULL,
    base_conhecimento TEXT NOT NULL,
    regras_horarios TEXT NOT NULL,
    taxa_entrega VARCHAR(100) NOT NULL,
    valor_isencao_taxa VARCHAR(100) NOT NULL,
    trabalha_genericos VARCHAR(10) NOT NULL,
    programa_preco_popular VARCHAR(10) NOT NULL,
    servicos_drogaria TEXT NOT NULL,
    gatilhos_transferencia_humano TEXT NOT NULL,
    formas_pagamento TEXT NOT NULL,
    modelo_pedido VARCHAR(50) NOT NULL,
    restricoes TEXT,
    observacoes TEXT,
    consentimento_lgpd BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
